// ==UserScript==
// @name               Poe
// @name:zh-CN         Poe
// @description        This Userscript is used to bypass the limitations of Poe and allows you to directly access the robots on Poe through the Safari browser, while also allowing you to freely select the text on the page. By using it together with Shortcuts, you can also automatically insert the selected text into the dialogue box and change font of the website.
// @description:zh-CN  此脚本用于绕过Poe的限制，允许你通过Safari浏览器直接访问Poe上的机器人，同时还允许你自由选择页面上的文本。通过将其与Shortcuts一起使用，还可以自动将所选文本插入对话框并更改字体。
// @author             Nickilism
// @version            20230501
// @license            DoWhatYouWant
// @namespace
// @include            poe\.*
// @grant              none
// @inject-into        content
// @run-at             document-start
// ==/UserScript==

// Shortcuts download link: https://www.icloud.com/shortcuts/f64c69c331ba4077af32cbb2a5972985

// The below code is all generated by Poe Bot https://poe.com/BotCoderN

// You need first change the request User-Agent with surge like apps:
//[Header Rewrite]
// ^https:\/\/(www\.)?poe\.com\/ header-replace User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.0.0"

(function () {
  // enbale text selection
  document.querySelectorAll("*").forEach(function (element) {
    element.style.setProperty("-webkit-user-select", "text", "important");
    element.style.setProperty("-webkit-touch-callout", "text", "important");
  });
  
  const url = window.location.href;
  // Extract the search parameters from the URL
  let searchParamsString = '';
  const queryStringIndex = url.indexOf('?');
  if (queryStringIndex !== -1) {
    searchParamsString = url.substring(queryStringIndex + 1);
	}
  // Parse the search parameters and extract the values
	
  const searchParams = new URLSearchParams(searchParamsString);
	
  const text = searchParams.get("text");
  const fontFamily = searchParams.get("fontFamily") ? searchParams.get("fontFamily"):'PingFangHK-Regular'
  const fontSize = searchParams.get("fontSize") ? searchParams.get("fontSize") : '14px'
  // If the text parameter is present, decode it and insert it into the chat input field

  if (text) {
    const decodedText = decodeURIComponent(text);
    const chatInput = document.querySelector(
      ".ChatMessageInputView_textInput__Aervw"
    );
    if (chatInput) {
      chatInput.value += decodedText;
			
    }
  }

  // add font sytle
  var style = document.createElement("style");
  style.type = "text/css";
  var head = document.head;
  head.appendChild(style);
  // change font here
  style.sheet.insertRule(
    `* { font-family: ${fontFamily}, cursive; font-size: ${fontSize}; }`
  );
	setTimeout(()=>{
		// Click the send button
      const sendButton = document.querySelector('.ChatMessageInputView_sendButton__reEpT');
      if (sendButton) {
           sendButton.click();
					
					}
	}, 500)
  completion(true);
})();