// ==UserScript==
// @name               Poe
// @name:zh-CN         Poe
// @description        This Userscript is used to bypass the limitations of Poe and allows you to directly access the robots on Poe through the Safari browser, while also allowing you to freely select the text on the page. By using it together with Shortcuts, you can also automatically insert the selected text into the dialogue box and change font of the website.
// @description:zh-CN  此脚本用于绕过Poe的限制，允许你通过Safari浏览器直接访问Poe上的机器人，同时还允许你自由选择页面上的文本。通过将其与Shortcuts一起使用，还可以自动将所选文本插入对话框并更改字体。
// @author             Nickilism
// @version            20230430
// @license            DoWhatYouWant
// @namespace
// @match              *://*.poe.com/*
// @grant              none
// @inject-into        content
// @run-at             document-start
// ==/UserScript==

// Shortcuts download link: https://www.icloud.com/shortcuts/c2e3f294ac554b7ba7e1c90780409487

// The below code is all generated by Poe Bot https://poe.com/BotCoderN

// Set new user agent string
const newUserAgent =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.0.0";

// Intercept and modify requests
const originalSend = XMLHttpRequest.prototype.send;
XMLHttpRequest.prototype.send = function () {
  this.setRequestHeader("User-Agent", newUserAgent);
  originalSend.apply(this, arguments);
};

(function () {
  // enbale text selection
  document.querySelectorAll("*").forEach(function (element) {
    element.style.setProperty("-webkit-user-select", "text", "important");
    element.style.setProperty("-webkit-touch-callout", "text", "important");
  });
  setTimeout(() => {
  const url = window.location.href;

  // Extract the search parameters from the URL
  const searchParamsString = url.substring(url.indexOf("?") + 1);
  // Parse the search parameters and extract the values
  const searchParams = new URLSearchParams(searchParamsString);
  const text = searchParams.get("text");
  const fontFamily = searchParams.get("fontFamily");
  const fontSize = searchParams.get("fontSize");
  // If the text parameter is present, decode it and insert it into the chat input field

  if (text) {
    const decodedText = decodeURIComponent(text);
    const chatInput = document.querySelector(
      ".ChatMessageInputView_textInput__Aervw"
    );
    if (chatInput) {
      chatInput.value += decodedText;
    }
  }

  if (!fontFamily) fontFamily = "PingFangHK-Regular";
  if (!fontSize) fontSize = "14px";
  // add font sytle
  var style = document.createElement("style");
  style.type = "text/css";
  var head = document.head;
  head.appendChild(style);
  // change font here
  style.sheet.insertRule(
    `* { font-family: ${fontFamily}, cursive; font-size: ${fontSize}; }`
  );

  completion(true);},100)
})();
