// ==UserScript==
// @name               Poe
// @name:zh-CN         Poe
// @description        This script enables direct access to a specific robot on Poe through the Safari browser, integrates seamlessly with Shortcuts, and allows for automatic insertion of selected text into a dialogue box and sending. It also supports customization of font sizes and styles on the page."
// @description:zh-CN  此脚本允许你通过Safari浏览器直接访问Poe上的特定机器人，同时与Shortcuts一起使用，还可以自动将所选文本插入对话框并发送，并支持更改页面上的字号和字体。
// @author             Nickilism
// @version            20240421
// @license            DoWhatYouWant
// @namespace
// @include            /^https?://poe\.com\/.*$/
// @grant              none
// @inject-into        content
// @run-at             document-end
// ==/UserScript==

// Shortcuts download link: https://www.icloud.com/shortcuts/08a620c2aad14c6997aea60a69216842

// The below code is all generated by Poe Bot https://poe.com/BotCoderN

// You need first change the request User-Agent with surge like apps:
//[Header Rewrite]
// ^https:\/\/(www\.)?poe\.com\/ header-replace User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.0.0"

(function () {
  // enbale text selection
  document.querySelectorAll("*").forEach(function (element) {
    element.style.setProperty("-webkit-user-select", "text", "important");
    element.style.setProperty("-webkit-touch-callout", "text", "important");
  });
  
  const url = window.location.href;
  // Extract the search parameters from the URL
  let searchParamsString = '';
  const queryStringIndex = url.indexOf('?');
  if (queryStringIndex !== -1) {
    searchParamsString = url.substring(queryStringIndex + 1);
	}
  // Parse the search parameters and extract the values
	
  const searchParams = new URLSearchParams(searchParamsString);
	
  const text = searchParams.get("text");
  const fontFamily = searchParams.get("fontFamily") ? searchParams.get("fontFamily"):'PingFangHK-Regular'
  const fontSize = searchParams.get("fontSize") ? searchParams.get("fontSize") : '14px'
  // If the text parameter is present, decode it and insert it into the chat input field
    // add font sytle
  var style = document.createElement("style");
  style.type = "text/css";
  var head = document.head;
  head.appendChild(style);
  // change font here
  style.sheet.insertRule(
    `* { font-family: ${fontFamily}, cursive; font-size: ${fontSize}; }`
		);

  if (text) {
    ( async() => {
      document.querySelector('textarea').value = text;
      // Step 1: Determine the target button
      const targetButtonClass = "Button_buttonBase__Bv9Vx Button_primary__6UIn0 ChatMessageSendButton_sendButton__4ZyI4 ChatMessageInputContainer_sendButton__dBjTt";

      // Step 2: Select the button element
      const targetButton = document.querySelector(`button[class="${targetButtonClass}"]`);
      document.querySelector('textarea').dispatchEvent(new Event('input'));
      document.querySelector('textarea').dispatchEvent(new Event('change'));
      await new Promise(r => setTimeout(r, 500));
      // Step 3: Simulate the click event
      targetButton.click();
      })();
  }

  completion(true);
})();